### ISSUE TITLE
Railway Integration

### ISSUE THREAD

**Issue by manikanta9176** [contentql/next-payload#28]
- [x] Store all the created project id's in a new collection Projects.
- [x] Fetch the created projects of the user from the railway.
- [x] Fetch the services of the project when user navigates to the service page.
- [ ] Sync the deployment status of the services using railway webhooks.
- [x] User can able deploy a github repo from the frontend itself.
- [x] Add types file

**Comment by jagadeesh507** [comment]
- [x] add popup box to create new services with three inputs id, name and github repo url
- [x] create service in railway from dashboard using railway graphql queries
- [x] delete service from railway using railway graphql queries

**Comment by manikanta9176** [comment]
Integration of webhooks will be addressed as a new issue (#35), to be processed at a later stage.
